### ISSUE TITLE
Plugin not working with Jest

### ISSUE THREAD

**Issue by norvalbv** [ElMassimo/vite-plugin-environment#13]
Hi,
We've recently switched from CRA to Vite and our testing is done with Jest. Half of our tests are using environment variables and if they're null or undefined it will throw an error.
I have in my plugins section within my `vite.config.ts` set the following like in your example:
```
  plugins: [react(), viteTsconfigPaths(), EnvironmentPlugin('all')],
```
However, when doing a `console.log()` on the envs, it works within the browser  (I get the values) but not within my Jest testing (I get undefined). I've gone around the configs for a while and it seems like this is an issue with this plugin not with Jest - the envs are not being passed correctly to Jest?

I was wondering if you could help.

**Comment by ElMassimo** [comment]
Hi Benjamin!

This plugin is a light wrapper around [`define`](https://vitejs.dev/config/shared-options.html#define).

I highly recommend switching from Jest to [Vitest](https://vitest.dev/guide/), as it's significantly faster and more robust, and `define` works as expected.
