### ISSUE TITLE
env variables don't work inside index.html

### ISSUE THREAD

**Issue by kouts** [ElMassimo/vite-plugin-environment#14]
Thank you for this wonderful plugin.

Although env variables work inside js/ts files, they don't work inside `index.html` using the `%MY_VAR%` syntax.
Context: https://github.com/vitejs/vite/issues/3105#issuecomment-1441947641

**Comment by ElMassimo** [comment]
Hi Giannis!

The HTML replacement will only [cover variables defined in `import.meta.env`](https://github.com/vitejs/vite/pull/12202/files#diff-89bae1df62862bb7f4a03d82a1e9cbf4ac6d0c042f21fbbacb0a2238bd050042R956).

You can expose variables under `import.meta.env` by [following this section](https://github.com/ElMassimo/vite-plugin-environment#exposing-variables-differently).

**Comment by kouts** [comment]
Thank you @ElMassimo that worked.
Example for future visitors:
```
environmentPlugin('all', { prefix: 'VUE_APP_' }),
environmentPlugin(['VUE_APP_MY_HTML_INJECTED_VAR'], { defineOn: 'import.meta.env' }),
```

It's good to point out that `VUE_APP_MY_HTML_INJECTED_VAR` will be injected with surrounding double quotes in `index.html` like `"{var_contents_here}"`.
