### ISSUE TITLE
Does this work with Netlify functions?

### ISSUE THREAD

**Issue by KenEucker** [ElMassimo/vite-plugin-environment#2]
I am using your plugin with success in the frontend code, but when I run `netlify dev` the environment variables are not there.

Has anyone else tried this with this package?

**Comment by KenEucker** [comment]
@ElMassimo,

It seems that my issues with accessing environment variables in Netlify functions was due to not setting the environment variables in the correct place, and needing to add a plugin for Netlify deployments specific to Netlify functions.

Not sure there's anything in there that can benefit the vite-plugin-community, as this was a misunderstanding on my part.

**Comment by ElMassimo** [comment]
Just sharing that is useful for anyone, thanks!
