### ISSUE TITLE
Cannot create property

### ISSUE THREAD

**Issue by 7flash** [ElMassimo/vite-plugin-environment#6]
![image](https://user-images.githubusercontent.com/4569866/169989392-d634d4e8-7291-43da-9956-58e929a081ef.png)

![image](https://user-images.githubusercontent.com/4569866/169989423-d59fa764-36f7-450b-a48e-fd517030c0b8.png)

![image](https://user-images.githubusercontent.com/4569866/169989504-124be6a4-7faf-412b-8447-7a8638c0e8c4.png)

**Comment by ElMassimo** [comment]
You have defined `process.env` to be `development`, so Vite will replace any occurrence of it:

```ts
process.env.REACT_APP_SUPABASE_URL
```

to:

```
'development'.REACT_APP_SUPABASE_URL
```

You probably wanted to define `process.env.NODE_ENV` instead.

**Comment by ElMassimo** [comment]
Also, I'd encourage you to use `import.meta.env.MODE` as an alternative instead of configuring that manually.
