### ISSUE TITLE
The plugin doesn't work with Vite v3

### ISSUE THREAD

**Issue by dotai2012** [ElMassimo/vite-plugin-environment#7]
Hi there, looks like this plugin doesn't support Vite v3

In v2, everything was fine, but when I upgrade to v3, it got the error:

`Uncaught ReferenceError: process is not defined`

**Comment by ElMassimo** [comment]
Please provide a full trace and a minimal reproduction 😃

**Comment by danielbayerlein** [comment]
I have the same problem. With `vite`(dev) it works without problems, but as soon as I run `vite build` and `vite preview` I get the `Uncaught ReferenceError: process is not defined` error.

Workaround:

```js
define: {
  'process.env': process.env
}
```

**Comment by ElMassimo** [comment]
@danielbayerlein Replacement is performed using [`define`](https://vitejs.dev/config/shared-options.html#define):

> Because it's implemented as straightforward text replacements without any syntax analysis, we recommend using define for CONSTANTS only.

That means that `process.env` won't be injected as a constant with values. Instead, `process.env.MY_VAR` will be replaced statically with the provided value.

**Comment by danielbayerlein** [comment]
@ElMassimo Thanks for the feedback. Without `'process.env': process.env` the error `Uncaught ReferenceError: process is not defined` occurs. Any ideas? Only occurs with Vite 3.

**Comment by danielbayerlein** [comment]
Yes I use `process.env`, however it should be replaced.

**Comment by ElMassimo** [comment]
In that case, you should probably use `JSON.stringify`, as in:

```ts
define: {
  'process.env': JSON.stringify(process.env),
}
```

However, I'd suggest not letting everything go through, and instead manually select the variables that your application uses.

**Comment by danielbayerlein** [comment]
But shouldn't the variables be replaced automatically? I'm trying to create an example.

**Comment by danielbayerlein** [comment]
My mistake! The problem occurs when a process.env variable cannot be resolved.
